import psycopg2
from datetime import date
from config import POSTGRES

# Conectar ao banco
def conectar():
    conn = psycopg2.connect(**POSTGRES)
    print("üîå Conectado ao banco:", conn.get_dsn_parameters()["dbname"])
    return conn




def popular_dim_categoria(cur):
    categorias = [
        (1, 'Eletr√¥nicos', 'Produtos eletr√¥nicos como celulares, TVs, computadores'),
        (2, 'Alimentos', 'Produtos aliment√≠cios e bebidas'),
        (3, 'Roupas', 'Vestu√°rio masculino, feminino e infantil'),
        (4, 'Cal√ßados', 'Sapatos, t√™nis e sand√°lias'),
        (5, 'M√≥veis', 'M√≥veis para casa e escrit√≥rio'),
        (6, 'Esportes', 'Equipamentos e roupas esportivas'),
        (7, 'Beleza', 'Produtos de beleza e higiene pessoal'),
        (8, 'Livros', 'Livros de todos os g√™neros e tipos'),
        (9, 'Brinquedos', 'Brinquedos e jogos para crian√ßas'),
        (10, 'Automotivo', 'Pe√ßas e acess√≥rios para ve√≠culos')
    ]

    for categoria in categorias:
        cur.execute("""
            INSERT INTO dim_categoria (id_categoria, nome_categoria, descricao)
            VALUES (%s, %s, %s)
            ON CONFLICT (id_categoria) DO NOTHING;
        """, categoria)

if __name__ == "__main__":
    conn = conectar()
    cur = conn.cursor()

    try:
        popular_dim_categoria(cur)
        conn.commit()
        print("‚úÖ Tabela dim_categoria populada com sucesso!")
    except Exception as e:
        print(f"‚ùå Erro ao popular a tabela dim_categoria: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()